// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OMSApp.Data.Migrations
{
    [DbContext(typeof(OMSDbContext))]
    [Migration("20260326000000_InitOMS")]
    partial class InitOMS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopper", b =>
            {
                b.Property<int>("IdShopper").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdShopper"));
                b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("FirstName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("LastName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Address").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("City").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("StateProvince").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Country").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ZipCode").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("IdShopper");
                b.ToTable("Shopper");
            });

            modelBuilder.Entity("Product", b =>
            {
                b.Property<int>("IdProduct").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));
                b.Property<string>("ProductName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.HasKey("IdProduct");
                b.ToTable("Product");
            });

            modelBuilder.Entity("Basket", b =>
            {
                b.Property<int>("IdBasket").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBasket"));
                b.Property<int>("IdShopper").HasColumnType("int");
                b.Property<int>("Quantity").HasColumnType("int");
                b.Property<decimal>("SubTotal").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.Property<DateTime>("OrderDate").HasColumnType("datetime2");
                b.HasKey("IdBasket");
                b.HasIndex("IdShopper");
                b.ToTable("Basket");
            });

            modelBuilder.Entity("BasketItem", b =>
            {
                b.Property<int>("IdBasketItem").HasColumnType("int");
                b.Property<int>("IdProduct").HasColumnType("int");
                b.Property<int>("Quantity").HasColumnType("int");
                b.Property<int>("IdBasket").HasColumnType("int");
                b.HasKey("IdBasketItem");
                b.HasIndex("IdBasket");
                b.HasIndex("IdProduct");
                b.ToTable("BasketItem");
            });

            modelBuilder.Entity("Basket", b =>
            {
                b.HasOne("Shopper", "Shopper")
                    .WithMany("Baskets")
                    .HasForeignKey("IdShopper")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Shopper");
            });

            modelBuilder.Entity("BasketItem", b =>
            {
                b.HasOne("Basket", "Basket")
                    .WithMany("BasketItems")
                    .HasForeignKey("IdBasket")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("Product", "Product")
                    .WithMany()
                    .HasForeignKey("IdProduct")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Basket");
                b.Navigation("Product");
            });

            modelBuilder.Entity("Shopper", b =>
            {
                b.Navigation("Baskets");
            });

            modelBuilder.Entity("Basket", b =>
            {
                b.Navigation("BasketItems");
            });
#pragma warning restore 612, 618
        }
    }
}
